# -*- coding: utf-8 -*-
"""kalkulatorspldv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYMtcXqBhnSqTa5EDq_Ru_Q3q4lcH2LM
"""

import streamlit as st

def solve_spldv(a1, b1, c1, a2, b2, c2):
    """Menyelesaikan SPLDV menggunakan metode Cramer atau substitusi/eliminasi."""
    determinan = a1 * b2 - a2 * b1
    if determinan == 0:
        return None, None, "Sistem memiliki tak hingga solusi atau tidak memiliki solusi (garis sejajar/berhimpit)."
    else:
        dx = c1 * b2 - c2 * b1
        dy = a1 * c2 - a2 * c1
        x = dx / determinan
        y = dy / determinan
        return x, y, None

st.set_page_config(layout="wide", page_title="Kalkulator SPLDV Interaktif")

st.title("Kalkulator SPLDV Interaktif dengan Discovery Learning")
st.markdown("""
Selamat datang di Kalkulator SPLDV Interaktif! 🚀
Di sini kamu akan belajar menyelesaikan sistem persamaan linear dua variabel (SPLDV) dengan metode **Discovery Learning**.
Artinya, kamu akan dibimbing untuk menemukan solusi sendiri!
""")

st.header("Langkah 1: Masukkan Persamaan SPLDV")
st.markdown("""
Bentuk umum SPLDV adalah:
$a_1x + b_1y = c_1$
$a_2x + b_2y = c_2$

Silakan masukkan koefisien-koefisiennya di bawah ini.
""")

col1, col2, col3 = st.columns(3)
with col1:
    st.subheader("Persamaan 1")
    a1 = st.number_input("Koefisien a1", value=1.0, key="a1")
    b1 = st.number_input("Koefisien b1", value=1.0, key="b1")
    c1 = st.number_input("Konstanta c1", value=5.0, key="c1")

with col2:
    st.subheader("Persamaan 2")
    a2 = st.number_input("Koefisien a2", value=2.0, key="a2")
    b2 = st.number_input("Koefisien b2", value=1.0, key="b2")
    c2 = st.number_input("Konstanta c2", value=7.0, key="c2")

st.write(f"Persamaan Anda: \n1) `{a1}x + {b1}y = {c1}`\n2) `{a2}x + {b2}y = {c2}`")

st.header("Langkah 2: Pahami Konsep (Petunjuk)")
st.markdown("""
Untuk menyelesaikan SPLDV, kita bisa menggunakan beberapa metode, seperti **substitusi**, **eliminasi**, atau **grafik**.
Mari kita coba memahami salah satu metode.

**Metode Eliminasi:**
Tujuan dari metode eliminasi adalah menghilangkan salah satu variabel (x atau y) untuk menemukan nilai variabel lainnya. Ini dilakukan dengan membuat koefisien salah satu variabel sama (atau berlawanan tanda) di kedua persamaan, lalu menjumlahkan atau mengurangkan persamaan tersebut.
""")

st.subheader("Petunjuk Interaktif:")
st.markdown("Coba pikirkan, bagaimana cara membuat koefisien 'x' atau 'y' sama di kedua persamaan?")

st.info("💡 **Tips:** Anda bisa mengalikan seluruh persamaan dengan suatu bilangan!")

st.header("Langkah 3: Coba Eliminasi Salah Satu Variabel")

st.markdown("Pilih variabel yang ingin Anda eliminasi:")
elim_var = st.radio("Variabel yang ingin dieliminasi:", ("x", "y"))

st.markdown(f"Untuk mengeliminasi **{elim_var}**, kita perlu mengalikan persamaan agar koefisien **{elim_var}** di kedua persamaan menjadi sama (atau berlawanan tanda).")

if elim_var == "x":
    st.write(f"Untuk mengeliminasi x, kita bisa mengalikan Persamaan 1 dengan **{a2}** dan Persamaan 2 dengan **{a1}**.")
    mult1_x = st.number_input("Kalikan Persamaan 1 dengan:", value=a2, key="mult1_x")
    mult2_x = st.number_input("Kalikan Persamaan 2 dengan:", value=a1, key="mult2_x")

    new_a1 = a1 * mult1_x
    new_b1 = b1 * mult1_x
    new_c1 = c1 * mult1_x

    new_a2 = a2 * mult2_x
    new_b2 = b2 * mult2_x
    new_c2 = c2 * mult2_x

    st.write(f"Persamaan baru Anda setelah dikalikan:")
    st.write(f"1') `{new_a1}x + {new_b1}y = {new_c1}`")
    st.write(f"2') `{new_a2}x + {new_b2}y = {new_c2}`")

    st.markdown("Sekarang, coba jumlahkan atau kurangkan kedua persamaan baru ini untuk menghilangkan 'x'.")
    operation_x = st.radio("Operasi yang ingin dilakukan:", ("Kurangkan (1' - 2')", "Jumlahkan (1' + 2')"))

    if operation_x == "Kurangkan (1' - 2')":
        res_a = new_a1 - new_a2
        res_b = new_b1 - new_b2
        res_c = new_c1 - new_c2
    else: # Jumlahkan
        res_a = new_a1 + new_a2
        res_b = new_b1 + new_b2
        res_c = new_c1 + new_c2

    st.write(f"Hasil setelah operasi: `{res_a}x + {res_b}y = {res_c}`")
    if abs(res_a) < 1e-9: # Memeriksa apakah koefisien x mendekati nol
        st.success(f"Hebat! Anda berhasil mengeliminasi 'x'. Sekarang Anda memiliki persamaan `{res_b}y = {res_c}`.")
        if res_b != 0:
            found_y = res_c / res_b
            st.write(f"Dari sini, Anda bisa menemukan nilai y: $y = {found_y:.2f}$")
        else:
            st.warning("Koefisien y juga nol. Periksa kembali persamaan atau operasinya.")
    else:
        st.error("Koefisien 'x' belum nol. Coba periksa kembali perkalian atau operasinya.")


elif elim_var == "y":
    st.write(f"Untuk mengeliminasi y, kita bisa mengalikan Persamaan 1 dengan **{b2}** dan Persamaan 2 dengan **{b1}**.")
    mult1_y = st.number_input("Kalikan Persamaan 1 dengan:", value=b2, key="mult1_y")
    mult2_y = st.number_input("Kalikan Persamaan 2 dengan:", value=b1, key="mult2_y")

    new_a1 = a1 * mult1_y
    new_b1 = b1 * mult1_y
    new_c1 = c1 * mult1_y

    new_a2 = a2 * mult2_y
    new_b2 = b2 * mult2_y
    new_c2 = c2 * mult2_y

    st.write(f"Persamaan baru Anda setelah dikalikan:")
    st.write(f"1') `{new_a1}x + {new_b1}y = {new_c1}`")
    st.write(f"2') `{new_a2}x + {new_b2}y = {new_c2}`")

    st.markdown("Sekarang, coba jumlahkan atau kurangkan kedua persamaan baru ini untuk menghilangkan 'y'.")
    operation_y = st.radio("Operasi yang ingin dilakukan:", ("Kurangkan (1' - 2')", "Jumlahkan (1' + 2')"))

    if operation_y == "Kurangkan (1' - 2')":
        res_a = new_a1 - new_a2
        res_b = new_b1 - new_b2
        res_c = new_c1 - new_c2
    else: # Jumlahkan
        res_a = new_a1 + new_a2
        res_b = new_b1 + new_b2
        res_c = new_c1 + new_c2

    st.write(f"Hasil setelah operasi: `{res_a}x + {res_b}y = {res_c}`")
    if abs(res_b) < 1e-9: # Memeriksa apakah koefisien y mendekati nol
        st.success(f"Hebat! Anda berhasil mengeliminasi 'y'. Sekarang Anda memiliki persamaan `{res_a}x = {res_c}`.")
        if res_a != 0:
            found_x = res_c / res_a
            st.write(f"Dari sini, Anda bisa menemukan nilai x: $x = {found_x:.2f}$")
        else:
            st.warning("Koefisien x juga nol. Periksa kembali persamaan atau operasinya.")
    else:
        st.error("Koefisien 'y' belum nol. Coba periksa kembali perkalian atau operasinya.")

st.header("Langkah 4: Verifikasi Jawaban Anda (Otomatis)")
st.markdown("Setelah Anda menemukan nilai x dan y, Anda bisa memverifikasi jawaban Anda di sini.")

if st.button("Lihat Solusi SPLDV"):
    x_sol, y_sol, error_msg = solve_spldv(a1, b1, c1, a2, b2, c2)
    if error_msg:
        st.error(f"Maaf, sistem persamaan ini {error_msg}")
    else:
        st.success(f"🎉 **Selamat!** Solusi SPLDV adalah:")
        st.write(f"Nilai $x = {x_sol:.2f}$")
        st.write(f"Nilai $y = {y_sol:.2f}$")

        st.subheader("Cek Jawaban Anda:")
        st.write(f"Untuk Persamaan 1: `{a1}*{x_sol:.2f} + {b1}*{y_sol:.2f} = {a1*x_sol + b1*y_sol:.2f}` (Seharusnya {c1})")
        st.write(f"Untuk Persamaan 2: `{a2}*{x_sol:.2f} + {b2}*{y_sol:.2f} = {a2*x_sol + b2*y_sol:.2f}` (Seharusnya {c2})")
        st.info("Jika hasil perhitungan mendekati nilai c1 dan c2, maka jawaban Anda benar!")

st.markdown("""
---
**Tentang Aplikasi Ini:**
Aplikasi ini dibuat untuk membantu Anda memahami konsep SPLDV dengan pendekatan discovery learning.
Anda diajak untuk mencoba langkah-langkah eliminasi dan memverifikasi hasilnya sendiri.
""")